### ISSUE TITLE
Java task list

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Base85#1]
Roughly in this order

- [x] Implement ZeroMQ/Z85.
- [x] Add test cases for invalid data.
- [x] Implement Ascii85
- [ ] NPM?
- [ ] Add stream helper and wrapper.
- [ ] Add Base64.Encoder/Decoder wrapper.
- [ ] Add [rafagafe](https://github.com/rafagafe/base85/blob/master/base85.c) and alt Z85 implementations to benchmark.
- [ ] Benchmark and make a chart.  Update readme to include example code.
- [ ] Add command line interface.
- [ ] See if a lite gui is feasible; the code should be pretty big by this step.
- [ ] Make a release and update project tags.
- [ ] Apache Maven?
